refactor(ui): 变更 loading 样式为 3 个小圆点
FEMessage/log-viewer pull request #4
Opened 2019-09-19 09:28 UTC by eviIIt

![loading-dots](https://user-images.githubusercontent.com/53422750/65231922-dfa41200-db02-11e9-988d-a1de6188ee6a.gif)

## Why

- 根据内部针对 Log Viewer 组件优化与迭代计划
- 外观灵感来源
  - zeit/design loading-dots
- 变更灵感来源
  - gitlab CI
  - travis CI
  - 以及其他...

## How

![image](https://user-images.githubusercontent.com/53422750/65229473-eb8dd500-dafe-11e9-9e4f-78d6a225c019.png)

## Test

```console
$ jest --verbose
 PASS  test/utils/index.test.js
  src/utils/index.js
    ✓ 根据换行符切割字符串 (6ms)
    ✓ 去除开头的控制符 (1ms)
    ✓ 去除尾部的控制符 (1ms)
    ✓ 删除K控制符之前的同一行内容 (2ms)
    ✓ 删除光标控制符

Test Suites: 1 passed, 1 total
Tests:       5 passed, 5 total
Snapshots:   0 total
Time:        3.892s
Ran all test suites.
```

## Credit

- [zeit/design's loading-dots](https://zeit.co/design/loading-dots)

2019-09-19 10:02 UTC, lianghx-319 approved these changes

2019-09-20 02:34 UTC, levy9527 requested changes

2019-09-20 02:34 UTC, levy9527 commented on src/components/loading.vue
>    <span class="log-loading">
缺少文档。README.md 截图不对。

2019-09-20 03:22 UTC, levy9527 approved these changes

2019-09-20 03:24 UTC, merged